CREATE DATABASE M_Peoples;

USE M_Peoples;

CREATE TABLE Funcionarios(
	IdFuncionario	INT PRIMARY KEY IDENTITY
	,Nome			VARCHAR(255) NOT NULL
	,Sobrenome		VARCHAR(255) NOT NULL
);

CREATE TABLE TipoUsuarios (
	IdTipoUsuario	INT PRIMARY KEY IDENTITY 
	,Titulo		VARCHAR(255) NOT NULL
);

CREATE TABLE Usuarios (
	IdUsuario	INT PRIMARY KEY IDENTITY
	,Email		VARCHAR(255) UNIQUE NOT NULL
	,Senha		VARCHAR(255) NOT NULL
	,IdTipoUsuario	INT FOREIGN KEY REFERENCES TipoUsuarios (IdTipoUsuario)
);